[project]
name = "muon-tutorial"
version = "0.1.0"
description = "Muon optimizer practice"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.9.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
]
